#!/usr/bin/env python3
#  Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
#  See https://llvm.org/LICENSE.txt for license information.
#  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""
Test MultiCycleALU (proc_example) with Verilator Simulation using PyCMT2 features.

This script demonstrates using the SimulationWorkspace and STL modules
from pycmt2 to create and run RTL simulations.

Usage:
    cd circt-cmt2/build
    PYTHONPATH=tools/circt/python_packages/circt_core python3 ../examples/PyCMT2/test_proc_simulation.py
"""

import shutil
from pathlib import Path

from circt.pycmt2 import Circuit, UInt
from circt.pycmt2.simulation import SimulationWorkspace
from circt.pycmt2.stl import Reg, clear_stl_registry


def create_alu_circuit():
    """Create the MultiCycleALU circuit using STL Reg modules."""
    # Clear any previous STL registry entries
    clear_stl_registry()

    circuit = Circuit("ProcCircuit")

    # Create register modules using STL
    reg32_mod = Reg.create(circuit, 32)
    reg1_mod = Reg.create(circuit, 1)

    with circuit.module("MultiCycleALU") as alu:
        clk = alu.clock("clk")
        rst = alu.reset("rst")

        # Internal state registers using STL Reg modules
        reg_a = alu.instance(reg32_mod, "reg_a", clk=clk, rst=rst)
        reg_b = alu.instance(reg32_mod, "reg_b", clk=clk, rst=rst)
        reg_result = alu.instance(reg32_mod, "reg_result", clk=clk, rst=rst)
        busy_reg = alu.instance(reg1_mod, "busy", clk=clk, rst=rst)

        # Method: start computation with operands
        with alu.method("start", args=[("a", UInt(32)), ("b", UInt(32))]) as meth:
            with meth.guard() as g:
                busy = g.call(busy_reg, "read")
                not_busy = g.not_(busy)
                g.returns(not_busy)
            with meth.body() as body:
                a_in = body.arg("a")
                b_in = body.arg("b")
                body.call(reg_a, "write", a_in)
                body.call(reg_b, "write", b_in)
                one = body.const(1, 1)
                body.call(busy_reg, "write", one)

        # Rule: compute result when busy
        with alu.rule("compute") as rule:
            with rule.guard() as g:
                busy = g.call(busy_reg, "read")
                g.returns(busy)
            with rule.body() as body:
                a = body.call(reg_a, "read")
                b = body.call(reg_b, "read")
                result = body.add(a, b)
                body.call(reg_result, "write", result)
                zero = body.const(0, 1)
                body.call(busy_reg, "write", zero)

        # Value method: read result
        with alu.value("get_result", returns=[UInt(32)]) as val:
            with val.guard() as g:
                busy = g.call(busy_reg, "read")
                not_busy = g.not_(busy)
                g.returns(not_busy)
            with val.body() as body:
                result = body.call(reg_result, "read")
                body.returns(result)

        # Value method: check if ready
        with alu.value("is_ready", returns=[UInt(1)]) as val:
            with val.guard() as g:
                g.always()
            with val.body() as body:
                busy = body.call(busy_reg, "read")
                not_busy = body.not_(busy)
                body.returns(not_busy)

    return circuit


# Custom testbench for ALU
ALU_TESTBENCH_CPP = """\
// MultiCycleALU Testbench
// Generated by PyCMT2 test_proc_simulation.py

#include "VMultiCycleALU.h"
#include "verilated.h"
#include "verilated_vcd_c.h"

#include <iostream>
#include <vector>

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Verilated::traceEverOn(true);

    auto dut = new VMultiCycleALU();
    auto tfp = new VerilatedVcdC();
    dut->trace(tfp, 99);
    tfp->open("waves/MultiCycleALU.vcd");

    // Initialize
    dut->clk = 0;
    dut->rst = 1;
    dut->start_enable = 0;
    dut->start_a = 0;
    dut->start_b = 0;

    int cycle = 0;
    bool all_passed = true;

    auto tick = [&]() {
        dut->clk = 0;
        dut->eval();
        tfp->dump(cycle * 10);
        dut->clk = 1;
        dut->eval();
        tfp->dump(cycle * 10 + 5);
        cycle++;
    };

    // Reset
    std::cout << "Resetting..." << std::endl;
    for (int i = 0; i < 5; i++) {
        tick();
    }
    dut->rst = 0;
    tick();

    // Test cases: (a, b, expected_sum)
    std::vector<std::tuple<uint32_t, uint32_t, uint32_t>> test_cases = {
        {10, 20, 30},
        {100, 200, 300},
        {0, 0, 0},
        {0xFFFFFFFF, 1, 0},  // Overflow (wraps to 0)
        {1234, 5678, 6912},
        {42, 0, 42},
    };

    for (const auto& [a, b, expected] : test_cases) {
        std::cout << "Testing " << a << " + " << b << " = " << expected << std::endl;

        // Check ready before starting
        if (!dut->start_ready) {
            std::cerr << "  ERROR: ALU not ready to start!" << std::endl;
            all_passed = false;
            continue;
        }

        // Start computation
        dut->start_a = a;
        dut->start_b = b;
        dut->start_enable = 1;
        tick();
        dut->start_enable = 0;

        // ALU should now be busy
        tick(); // Allow one cycle for state to update

        // Wait for result (max 10 cycles)
        int wait_cycles = 0;
        while (!dut->get_result_ready && wait_cycles < 10) {
            tick();
            wait_cycles++;
        }

        if (wait_cycles >= 10) {
            std::cerr << "  TIMEOUT: computation did not complete" << std::endl;
            all_passed = false;
            continue;
        }

        uint32_t result = dut->get_result_res0;
        if (result != expected) {
            std::cerr << "  FAIL: result = " << result << ", expected " << expected << std::endl;
            all_passed = false;
        } else {
            std::cout << "  PASS: result = " << result << std::endl;
        }

        // Wait a cycle before next test
        tick();
    }

    tfp->close();
    delete tfp;
    delete dut;

    if (all_passed) {
        std::cout << "\\nALL TESTS PASSED!" << std::endl;
        return 0;
    } else {
        std::cerr << "\\nSOME TESTS FAILED!" << std::endl;
        return 1;
    }
}
"""


def main():
    print("=" * 60)
    print("MultiCycleALU Simulation Test (using pycmt2 STL modules)")
    print("=" * 60)

    # Setup paths
    script_dir = Path(__file__).parent
    sim_dir = script_dir / "sim_alu"

    # Clean previous simulation
    if sim_dir.exists():
        shutil.rmtree(sim_dir)

    # Create circuit
    print("\n1. Creating MultiCycleALU circuit with STL Reg modules...")
    circuit = create_alu_circuit()

    # Create simulation workspace
    print("2. Setting up simulation workspace...")
    ws = SimulationWorkspace(circuit, sim_dir)

    # Generate workspace - STL RTL files are auto-added
    ws._add_stl_rtl()  # Add STL RTL files from registry
    ws._create_directories()
    ws._generate_rtl()
    ws._generate_makefile()

    # Write custom testbench
    tb_file = sim_dir / "tb" / "testbench.cpp"
    tb_file.write_text(ALU_TESTBENCH_CPP)

    print("3. Workspace generated at:", sim_dir)

    # Build simulation
    print("4. Building simulation...")
    if not ws.build():
        return 1
    print("   Build successful!")

    # Run simulation
    print("5. Running simulation...")
    success, output = ws.run()
    print(output)

    if not success:
        print("Simulation failed!")
        return 1

    print("\n" + "=" * 60)
    print("Simulation completed!")
    print(f"Waveforms available at: {sim_dir / 'waves' / 'MultiCycleALU.vcd'}")
    print("=" * 60)
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
