#!/usr/bin/env python3
#  Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
#  See https://llvm.org/LICENSE.txt for license information.
#  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""
Test GCD Example with Verilator Simulation using PyCMT2 features.

This script demonstrates using the SimulationWorkspace and STL modules
from pycmt2 to create and run RTL simulations.

Usage:
    cd circt-cmt2/build
    PYTHONPATH=tools/circt/python_packages/circt_core python3 ../examples/PyCMT2/test_gcd_simulation.py
"""

import shutil
from pathlib import Path

from circt.pycmt2 import Circuit, UInt
from circt.pycmt2.simulation import SimulationWorkspace
from circt.pycmt2.stl import Reg, clear_stl_registry


def create_gcd_circuit():
    """Create the GCD circuit using STL Reg modules."""
    # Clear any previous STL registry entries
    clear_stl_registry()

    circuit = Circuit("GCD")

    # Create 32-bit register module using STL
    reg_mod = Reg.create(circuit, 32)

    with circuit.module("GCD") as m:
        clk = m.clock()
        rst = m.reset()

        # State registers using STL Reg module
        reg_a = m.instance(reg_mod, "reg_a", clk=clk, rst=rst)
        reg_b = m.instance(reg_mod, "reg_b", clk=clk, rst=rst)

        # Method: load - Load input values
        with m.method("load", args=[("a", UInt(32)), ("b", UInt(32))]) as meth:
            with meth.guard() as g:
                g.always()
            with meth.body() as body:
                a_in = body.arg("a")
                b_in = body.arg("b")
                body.call(reg_a, "write", a_in)
                body.call(reg_b, "write", b_in)

        # Rule: compute - One iteration of GCD algorithm
        with m.rule("compute") as rule:
            with rule.guard() as g:
                b_val = g.call(reg_b, "read")
                zero = g.const(0, 32)
                cond = g.neq(b_val, zero)
                g.returns(cond)
            with rule.body() as body:
                a_val = body.call(reg_a, "read")
                b_val = body.call(reg_b, "read")
                a_gt_b = body.gt(a_val, b_val)
                new_a = body.sub(a_val, b_val)
                new_b = body.sub(b_val, a_val)
                final_a = body.mux(a_gt_b, new_a, a_val)
                final_b = body.mux(a_gt_b, b_val, new_b)
                body.call(reg_a, "write", final_a)
                body.call(reg_b, "write", final_b)

        # Value method: result - Read the GCD result
        with m.value("result", returns=[UInt(32)]) as val:
            with val.guard() as g:
                b_val = g.call(reg_b, "read")
                zero = g.const(0, 32)
                ready = g.eq(b_val, zero)
                g.returns(ready)
            with val.body() as body:
                result = body.call(reg_a, "read")
                body.returns(result)

    return circuit


# Custom testbench for GCD (the DSL doesn't yet support complex control flow)
GCD_TESTBENCH_CPP = """\
// GCD Testbench
// Generated by PyCMT2 test_gcd_simulation.py

#include "VGCD.h"
#include "verilated.h"
#include "verilated_vcd_c.h"

#include <iostream>
#include <vector>

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Verilated::traceEverOn(true);

    auto dut = new VGCD();
    auto tfp = new VerilatedVcdC();
    dut->trace(tfp, 99);
    tfp->open("waves/GCD.vcd");

    // Initialize
    dut->clk = 0;
    dut->rst = 1;
    dut->load_enable = 0;
    dut->load_a = 0;
    dut->load_b = 0;

    int cycle = 0;
    bool all_passed = true;

    auto tick = [&]() {
        dut->clk = 0;
        dut->eval();
        tfp->dump(cycle * 10);
        dut->clk = 1;
        dut->eval();
        tfp->dump(cycle * 10 + 5);
        cycle++;
    };

    // Reset
    std::cout << "Resetting..." << std::endl;
    for (int i = 0; i < 5; i++) {
        tick();
    }
    dut->rst = 0;
    tick();

    // Test cases: (a, b, expected_gcd)
    std::vector<std::tuple<uint32_t, uint32_t, uint32_t>> test_cases = {
        {48, 18, 6},
        {100, 80, 20},
        {17, 13, 1},
        {270, 192, 6},
        {12, 12, 12},
        {54, 24, 6},
        {35, 14, 7},
        {21, 14, 7},
    };

    for (const auto& [a, b, expected] : test_cases) {
        std::cout << "Testing GCD(" << a << ", " << b << ") = " << expected << std::endl;

        // Load values
        dut->load_a = a;
        dut->load_b = b;
        dut->load_enable = 1;
        tick();
        dut->load_enable = 0;

        // Wait for result (max 100 cycles)
        int wait_cycles = 0;
        while (!dut->result_ready && wait_cycles < 100) {
            tick();
            wait_cycles++;
        }

        if (wait_cycles >= 100) {
            std::cerr << "  TIMEOUT: did not complete" << std::endl;
            all_passed = false;
            continue;
        }

        uint32_t result = dut->result_res0;
        if (result != expected) {
            std::cerr << "  FAIL: result = " << result << ", expected " << expected << std::endl;
            all_passed = false;
        } else {
            std::cout << "  PASS: result = " << result << " (took " << wait_cycles << " cycles)" << std::endl;
        }

        tick();
    }

    tfp->close();
    delete tfp;
    delete dut;

    if (all_passed) {
        std::cout << "\\nALL TESTS PASSED!" << std::endl;
        return 0;
    } else {
        std::cerr << "\\nSOME TESTS FAILED!" << std::endl;
        return 1;
    }
}
"""


def main():
    print("=" * 60)
    print("GCD Simulation Test (using pycmt2 STL modules)")
    print("=" * 60)

    # Setup paths
    script_dir = Path(__file__).parent
    sim_dir = script_dir / "sim_gcd"

    # Clean previous simulation
    if sim_dir.exists():
        shutil.rmtree(sim_dir)

    # Create circuit
    print("\n1. Creating GCD circuit with STL Reg modules...")
    circuit = create_gcd_circuit()

    # Create simulation workspace
    print("2. Setting up simulation workspace...")
    ws = SimulationWorkspace(circuit, sim_dir)

    # Generate workspace - STL RTL files are auto-added
    ws._add_stl_rtl()  # Add STL RTL files from registry
    ws._create_directories()
    ws._generate_rtl()
    ws._generate_makefile()

    # Write custom testbench
    tb_file = sim_dir / "tb" / "testbench.cpp"
    tb_file.write_text(GCD_TESTBENCH_CPP)

    print("3. Workspace generated at:", sim_dir)

    # Build simulation
    print("4. Building simulation...")
    if not ws.build():
        return 1
    print("   Build successful!")

    # Run simulation
    print("5. Running simulation...")
    success, output = ws.run()
    print(output)

    if not success:
        print("Simulation failed!")
        return 1

    print("\n" + "=" * 60)
    print("Simulation completed!")
    print(f"Waveforms available at: {sim_dir / 'waves' / 'GCD.vcd'}")
    print("=" * 60)
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
