#!/bin/bash
#===- build.sh - Build script for FloPoCo IP modules --------------*- Bash -*-===#
#
# Generates FIRRTL extmodule declarations for FloPoCo-based floating-point IPs
# Also generates filelist.f for synthesis tools
#
# Parameters:
#   op       - Operation type: add, sub, mul, div, sqrt
#   width    - Data width (16, 32, 64)
#   latency  - Pipeline latency
#
# Outputs:
#   <module_name>.mlir  - FIRRTL extmodule with BlackBoxPathAnno
#   <module_name>.f     - Filelist for synthesis tools
#
# Supported latencies:
#   FMA (add/sub/mul) float32: 1, 2, 3, 4, 6
#   Div float32: 2, 4, 5, 7, 8, 12
#   Sqrt float32: 2, 4, 5, 7, 9, 12
#
#===------------------------------------------------------------------------===#

set -e

# Default parameters
OP="add"
WIDTH=32
LATENCY=4

# Parse named parameters
for arg in "$@"; do
  case $arg in
    op=*)
      OP="${arg#*=}"
      ;;
    width=*)
      WIDTH="${arg#*=}"
      ;;
    latency=*)
      LATENCY="${arg#*=}"
      ;;
    *)
      echo "Unknown parameter: $arg" >&2
      ;;
  esac
done

# Get script directory for Verilog file paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# FloPoCo source directory
FLOPOCO_SV_LIB="$(cd "${SCRIPT_DIR}/../../../../../../../flopoco-sv-lib" 2>/dev/null && pwd)"

# Common FloPoCo dependencies (format converters)
COMMON_DEPS=(
  "${FLOPOCO_SV_LIB}/flopoco/IEEE2FP/IEEE2FP_S0.v"
  "${FLOPOCO_SV_LIB}/flopoco/FP2IEEE/FP2IEEE_S0.v"
  "${FLOPOCO_SV_LIB}/rtl/wrappers/IEEE2FP.sv"
  "${FLOPOCO_SV_LIB}/rtl/wrappers/FP2IEEE.sv"
)

# FIFO module dependency
FIFO_DIR="$(cd "${SCRIPT_DIR}/../fifo" 2>/dev/null && pwd)"
FIFO_DEP="${FIFO_DIR}/fifo.sv"

# Function to generate BlackBoxPathAnno array
generate_annotations() {
  local wrapper_file="$1"
  shift
  local deps=("$@")

  local annos="{class = \"firrtl.transforms.BlackBoxPathAnno\", path = \"${wrapper_file}\"}"
  for dep in "${deps[@]}"; do
    annos="${annos}, {class = \"firrtl.transforms.BlackBoxPathAnno\", path = \"${dep}\"}"
  done
  echo "[${annos}]"
}

# Function to generate filelist
generate_filelist() {
  local filelist="$1"
  local wrapper_file="$2"
  shift 2
  local deps=("$@")

  {
    echo "// Filelist for ${MODULE_NAME}"
    echo "// Generated by build.sh (FloPoCo)"
    echo ""
    echo "// Wrapper module"
    echo "${wrapper_file}"
    echo ""
    echo "// FloPoCo dependencies"
    for dep in "${deps[@]}"; do
      echo "${dep}"
    done
  } > "${filelist}"
}

# Determine precision prefix for FloPoCo module names
if [ "$WIDTH" -eq 16 ]; then
  PREC="H"
elif [ "$WIDTH" -eq 32 ]; then
  PREC="S"
elif [ "$WIDTH" -eq 64 ]; then
  PREC="D"
else
  echo "Unsupported width: $WIDTH" >&2
  exit 1
fi

# Generate module name and output file based on operation
case $OP in
  add)
    MODULE_NAME="FloatAdd_w${WIDTH}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/FloatAdd.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/IEEEFMA/IEEEFMA_${PREC}$((LATENCY-1)).v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/IEEEFMA.sv"
      "${FIFO_DEP}"
    )
    ;;
  sub)
    MODULE_NAME="FloatSub_w${WIDTH}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/FloatSub.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/IEEEFMA/IEEEFMA_${PREC}$((LATENCY-1)).v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/IEEEFMA.sv"
      "${FIFO_DEP}"
    )
    ;;
  mul)
    MODULE_NAME="FloatMul_w${WIDTH}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/FloatMul.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/IEEEFMA/IEEEFMA_${PREC}$((LATENCY-1)).v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/IEEEFMA.sv"
      "${FIFO_DEP}"
    )
    ;;
  div)
    MODULE_NAME="FloatDiv_w${WIDTH}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/FloatDiv.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/FPDiv/FPDiv_${PREC}$((LATENCY-1)).v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/FPDiv.sv"
      "${FLOPOCO_SV_LIB}/rtl/IEEEDiv.sv"
      "${FIFO_DEP}"
    )
    ;;
  sqrt)
    MODULE_NAME="FloatSqrt_w${WIDTH}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/FloatSqrt.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/FPSqrt/FPSqrt_${PREC}$((LATENCY-1)).v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/FPSqrt.sv"
      "${FLOPOCO_SV_LIB}/rtl/IEEESqrt.sv"
      "${FIFO_DEP}"
    )
    ;;
  *)
    echo "Unknown operation: $OP" >&2
    echo "Supported operations: add, sub, mul, div, sqrt" >&2
    exit 1
    ;;
esac

MLIR_FILE="${SCRIPT_DIR}/${MODULE_NAME}.mlir"
FILELIST="${SCRIPT_DIR}/${MODULE_NAME}.f"

# Combine all dependencies
ALL_DEPS=("${OP_DEPS[@]}" "${COMMON_DEPS[@]}")

# Generate annotations
ANNOTATIONS=$(generate_annotations "${WRAPPER_FILE}" "${ALL_DEPS[@]}")

# Determine base module name (without parameters)
case $OP in
  add) BASE_NAME="FloatAdd" ;;
  sub) BASE_NAME="FloatSub" ;;
  mul) BASE_NAME="FloatMul" ;;
  div) BASE_NAME="FloatDiv" ;;
  sqrt) BASE_NAME="FloatSqrt" ;;
esac

# Generate MLIR file with correct syntax
cat > "${MLIR_FILE}" << EOF
module {
  firrtl.circuit "${MODULE_NAME}" {
EOF

# Add operand ports based on operation
if [ "$OP" = "sqrt" ]; then
  cat >> "${MLIR_FILE}" << EOF
    firrtl.extmodule @${MODULE_NAME}<WIDTH: i64 = ${WIDTH}, LATENCY: i64 = ${LATENCY}>(
      in clock: !firrtl.clock,
      in reset: !firrtl.uint<1>,
      in ce: !firrtl.uint<1>,
      in operand0: !firrtl.uint<${WIDTH}>,
      in rd_en: !firrtl.uint<1>,
      out rd_data: !firrtl.uint<${WIDTH}>,
      out rd_ready: !firrtl.uint<1>,
      out input_ready: !firrtl.uint<1>
    ) attributes {defname = "${BASE_NAME}", annotations = ${ANNOTATIONS}}
EOF
else
  cat >> "${MLIR_FILE}" << EOF
    firrtl.extmodule @${MODULE_NAME}<WIDTH: i64 = ${WIDTH}, LATENCY: i64 = ${LATENCY}>(
      in clock: !firrtl.clock,
      in reset: !firrtl.uint<1>,
      in ce: !firrtl.uint<1>,
      in operand0: !firrtl.uint<${WIDTH}>,
      in operand1: !firrtl.uint<${WIDTH}>,
      in rd_en: !firrtl.uint<1>,
      out rd_data: !firrtl.uint<${WIDTH}>,
      out rd_ready: !firrtl.uint<1>,
      out input_ready: !firrtl.uint<1>
    ) attributes {defname = "${BASE_NAME}", annotations = ${ANNOTATIONS}}
EOF
fi

cat >> "${MLIR_FILE}" << EOF
  }
}
EOF

# Generate filelist
generate_filelist "${FILELIST}" "${WRAPPER_FILE}" "${ALL_DEPS[@]}"

echo "Generated: ${MLIR_FILE}"
echo "Generated: ${FILELIST}"
