#!/bin/bash
#===- build.sh - Build script for FloPoCo IP modules --------------*- Bash -*-===#
#
# Generates FIRRTL extmodule declarations for FloPoCo-based floating-point IPs
# Also generates filelist.f for synthesis tools
#
# Parameters:
#   op        - Operation type: add, sub, mul, div, sqrt, exp, log, cmp, i2f, f2i
#   width     - Data width (16, 32, 64)
#   latency   - Pipeline latency
#   predicate - For cmp: 0=eq, 1=lt, 2=le, 3=gt, 4=ge, 5=ne, 6=ord, 7=uno
#
# Outputs:
#   <module_name>.mlir  - FIRRTL extmodule with BlackBoxPathAnno
#   <module_name>.f     - Filelist for synthesis tools
#
# Supported latencies:
#   FMA (add/sub/mul) float32: 2, 3, 4, 5, 7
#   Div float32: 3, 5, 6, 8, 9, 13
#   Sqrt float32: 3, 5, 6, 8, 10, 13
#   Exp float32: 4, 5, 6, 7, 8, 10
#   Log float32: 3, 4, 5, 6, 7, 10
#   Cmp: 1, 2, 3 (combinational + pipeline)
#   I2F/F2I float32: 1, 2, 3
#
#===------------------------------------------------------------------------===#

set -e

# Default parameters
OP="add"
WIDTH=32
LATENCY=4
PREDICATE=0
PRECISION=0  # For sincos only (0 means auto-detect from width)

# Parse named parameters
for arg in "$@"; do
  case $arg in
    op=*)
      OP="${arg#*=}"
      ;;
    width=*)
      WIDTH="${arg#*=}"
      ;;
    latency=*)
      LATENCY="${arg#*=}"
      ;;
    predicate=*)
      PREDICATE="${arg#*=}"
      ;;
    precision=*)
      PRECISION="${arg#*=}"
      ;;
    *)
      echo "Unknown parameter: $arg" >&2
      ;;
  esac
done

# Get script directory for Verilog file paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# FloPoCo source directory
FLOPOCO_SV_LIB="$(cd "${SCRIPT_DIR}/../../../../../../../flopoco-sv-lib" 2>/dev/null && pwd)"

# Common FloPoCo dependencies (format converters)
COMMON_DEPS=(
  "${FLOPOCO_SV_LIB}/flopoco/IEEE2FP/IEEE2FP_S0.v"
  "${FLOPOCO_SV_LIB}/flopoco/FP2IEEE/FP2IEEE_S0.v"
  "${FLOPOCO_SV_LIB}/rtl/wrappers/IEEE2FP.sv"
  "${FLOPOCO_SV_LIB}/rtl/wrappers/FP2IEEE.sv"
)

# FIFO module dependency
FIFO_DIR="$(cd "${SCRIPT_DIR}/../fifo" 2>/dev/null && pwd)"
FIFO_DEP="${FIFO_DIR}/fifo.sv"

# Function to generate BlackBoxPathAnno array
generate_annotations() {
  local wrapper_file="$1"
  shift
  local deps=("$@")

  local annos="{class = \"firrtl.transforms.BlackBoxPathAnno\", path = \"${wrapper_file}\"}"
  for dep in "${deps[@]}"; do
    annos="${annos}, {class = \"firrtl.transforms.BlackBoxPathAnno\", path = \"${dep}\"}"
  done
  echo "[${annos}]"
}

# Function to generate filelist
generate_filelist() {
  local filelist="$1"
  local wrapper_file="$2"
  shift 2
  local deps=("$@")

  {
    echo "// Filelist for ${MODULE_NAME}"
    echo "// Generated by build.sh (FloPoCo)"
    echo ""
    echo "// Wrapper module"
    echo "${wrapper_file}"
    echo ""
    echo "// FloPoCo dependencies"
    for dep in "${deps[@]}"; do
      echo "${dep}"
    done
  } > "${filelist}"
}

# Determine precision prefix for FloPoCo module names
if [ "$WIDTH" -eq 16 ]; then
  PREC="H"
elif [ "$WIDTH" -eq 32 ]; then
  PREC="S"
elif [ "$WIDTH" -eq 64 ]; then
  PREC="D"
else
  echo "Unsupported width: $WIDTH" >&2
  exit 1
fi

# Generate module name and output file based on operation
case $OP in
  add)
    MODULE_NAME="FloatAdd_w${WIDTH}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/FloatAdd.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/IEEEFMA/IEEEFMA_${PREC}$((LATENCY-1)).v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/IEEEFMA.sv"
      "${FIFO_DEP}"
    )
    ;;
  sub)
    MODULE_NAME="FloatSub_w${WIDTH}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/FloatSub.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/IEEEFMA/IEEEFMA_${PREC}$((LATENCY-1)).v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/IEEEFMA.sv"
      "${FIFO_DEP}"
    )
    ;;
  mul)
    MODULE_NAME="FloatMul_w${WIDTH}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/FloatMul.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/IEEEFMA/IEEEFMA_${PREC}$((LATENCY-1)).v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/IEEEFMA.sv"
      "${FIFO_DEP}"
    )
    ;;
  div)
    MODULE_NAME="FloatDiv_w${WIDTH}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/FloatDiv.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/FPDiv/FPDiv_${PREC}$((LATENCY-1)).v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/FPDiv.sv"
      "${FLOPOCO_SV_LIB}/rtl/IEEEDiv.sv"
      "${FIFO_DEP}"
    )
    ;;
  sqrt)
    MODULE_NAME="FloatSqrt_w${WIDTH}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/FloatSqrt.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/FPSqrt/FPSqrt_${PREC}$((LATENCY-1)).v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/FPSqrt.sv"
      "${FLOPOCO_SV_LIB}/rtl/IEEESqrt.sv"
      "${FIFO_DEP}"
    )
    ;;
  exp)
    MODULE_NAME="FloatExp_w${WIDTH}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/FloatExp.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/IEEEExp/IEEEExp_${PREC}$((LATENCY-1)).v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/IEEEExp.sv"
      "${FIFO_DEP}"
    )
    # IEEEExp uses IEEE format directly, no need for format converters
    COMMON_DEPS=()
    ;;
  log)
    MODULE_NAME="FloatLog_w${WIDTH}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/FloatLog.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/FPLog/FPLog_${PREC}$((LATENCY-1)).v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/FPLog.sv"
      "${FIFO_DEP}"
    )
    ;;
  cmp)
    MODULE_NAME="FloatCmp_w${WIDTH}_p${PREDICATE}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/FloatCmp.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/FPComp/FPComp_${PREC}0.v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/FPComp.sv"
      "${FLOPOCO_SV_LIB}/rtl/IEEEComp.sv"
      "${FIFO_DEP}"
    )
    ;;
  i2f)
    MODULE_NAME="Int2Float_w${WIDTH}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/Int2Float.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/Fix2FP/Fix2FP_${PREC}$((LATENCY-1)).v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/INT2FP.sv"
      "${FIFO_DEP}"
    )
    ;;
  f2i)
    MODULE_NAME="Float2Int_w${WIDTH}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/Float2Int.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/FP2Fix/FP2Fix_${PREC}$((LATENCY-1)).v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/FP2INT.sv"
      "${FIFO_DEP}"
    )
    ;;
  sincos)
    # FixSinCos uses precision (fractional bits) instead of width
    # precision=24 for float32, precision=11 for float16
    # Can be specified directly via precision= or mapped from width=
    if [ "$PRECISION" -ne 0 ]; then
      # Precision specified directly
      SINCOS_PREC=$PRECISION
    elif [ "$WIDTH" -eq 16 ]; then
      SINCOS_PREC=11
    elif [ "$WIDTH" -eq 32 ]; then
      SINCOS_PREC=24
    else
      echo "Unsupported width for sincos: $WIDTH (use 16 or 32, or specify precision=11/24)" >&2
      exit 1
    fi
    # Validate precision
    if [ "$SINCOS_PREC" -ne 11 ] && [ "$SINCOS_PREC" -ne 24 ]; then
      echo "Unsupported precision for sincos: $SINCOS_PREC (use 11 or 24)" >&2
      exit 1
    fi
    MODULE_NAME="FixSinCos_p${SINCOS_PREC}_l${LATENCY}"
    WRAPPER_FILE="${SCRIPT_DIR}/FixSinCos.v"
    OP_DEPS=(
      "${FLOPOCO_SV_LIB}/flopoco/FixSinCos/FixSinCos_${SINCOS_PREC}_S$((LATENCY-1)).v"
      "${FLOPOCO_SV_LIB}/rtl/wrappers/FixSinCos.sv"
      "${FIFO_DEP}"
    )
    # FixSinCos doesn't need IEEE format converters
    COMMON_DEPS=()
    ;;
  *)
    echo "Unknown operation: $OP" >&2
    echo "Supported operations: add, sub, mul, div, sqrt, exp, log, cmp, i2f, f2i, sincos" >&2
    exit 1
    ;;
esac

MLIR_FILE="${SCRIPT_DIR}/${MODULE_NAME}.mlir"
FILELIST="${SCRIPT_DIR}/${MODULE_NAME}.f"

# Combine all dependencies
ALL_DEPS=("${OP_DEPS[@]}" "${COMMON_DEPS[@]}")

# Generate annotations
ANNOTATIONS=$(generate_annotations "${WRAPPER_FILE}" "${ALL_DEPS[@]}")

# Determine base module name (without parameters)
case $OP in
  add) BASE_NAME="FloatAdd" ;;
  sub) BASE_NAME="FloatSub" ;;
  mul) BASE_NAME="FloatMul" ;;
  div) BASE_NAME="FloatDiv" ;;
  sqrt) BASE_NAME="FloatSqrt" ;;
  exp) BASE_NAME="FloatExp" ;;
  log) BASE_NAME="FloatLog" ;;
  cmp) BASE_NAME="FloatCmp" ;;
  i2f) BASE_NAME="Int2Float" ;;
  f2i) BASE_NAME="Float2Int" ;;
  sincos) BASE_NAME="FixSinCos" ;;
esac

# Generate MLIR file with correct syntax
cat > "${MLIR_FILE}" << EOF
module {
  firrtl.circuit "${MODULE_NAME}" {
EOF

# Add operand ports based on operation type
case $OP in
  # Single operand operations (unary)
  sqrt|exp|log|i2f|f2i)
    cat >> "${MLIR_FILE}" << EOF
    firrtl.extmodule @${MODULE_NAME}<WIDTH: i64 = ${WIDTH}, LATENCY: i64 = ${LATENCY}>(
      in clock: !firrtl.clock,
      in reset: !firrtl.uint<1>,
      in ce: !firrtl.uint<1>,
      in operand0: !firrtl.uint<${WIDTH}>,
      in rd_en: !firrtl.uint<1>,
      out rd_data: !firrtl.uint<${WIDTH}>,
      out rd_ready: !firrtl.uint<1>,
      out input_ready: !firrtl.uint<1>
    ) attributes {defname = "${BASE_NAME}", annotations = ${ANNOTATIONS}}
EOF
    ;;
  # Comparison operation (two operands, 1-bit output)
  cmp)
    cat >> "${MLIR_FILE}" << EOF
    firrtl.extmodule @${MODULE_NAME}<WIDTH: i64 = ${WIDTH}, PREDICATE: i64 = ${PREDICATE}, LATENCY: i64 = ${LATENCY}>(
      in clock: !firrtl.clock,
      in reset: !firrtl.uint<1>,
      in ce: !firrtl.uint<1>,
      in operand0: !firrtl.uint<${WIDTH}>,
      in operand1: !firrtl.uint<${WIDTH}>,
      in rd_en: !firrtl.uint<1>,
      out rd_data: !firrtl.uint<1>,
      out rd_ready: !firrtl.uint<1>,
      out input_ready: !firrtl.uint<1>
    ) attributes {defname = "${BASE_NAME}", annotations = ${ANNOTATIONS}}
EOF
    ;;
  # Sincos operation (single operand, two outputs: sin and cos)
  sincos)
    # FixSinCos uses PRECISION parameter, port width is PRECISION+1
    SINCOS_WIDTH=$((SINCOS_PREC + 1))
    cat >> "${MLIR_FILE}" << EOF
    firrtl.extmodule @${MODULE_NAME}<PRECISION: i64 = ${SINCOS_PREC}, LATENCY: i64 = ${LATENCY}>(
      in clock: !firrtl.clock,
      in reset: !firrtl.uint<1>,
      in ce: !firrtl.uint<1>,
      in operand0: !firrtl.uint<${SINCOS_WIDTH}>,
      in rd_en: !firrtl.uint<1>,
      out sin_data: !firrtl.uint<${SINCOS_WIDTH}>,
      out cos_data: !firrtl.uint<${SINCOS_WIDTH}>,
      out rd_ready: !firrtl.uint<1>,
      out input_ready: !firrtl.uint<1>
    ) attributes {defname = "${BASE_NAME}", annotations = ${ANNOTATIONS}}
EOF
    ;;
  # Binary operations (two operands, same width output)
  *)
    cat >> "${MLIR_FILE}" << EOF
    firrtl.extmodule @${MODULE_NAME}<WIDTH: i64 = ${WIDTH}, LATENCY: i64 = ${LATENCY}>(
      in clock: !firrtl.clock,
      in reset: !firrtl.uint<1>,
      in ce: !firrtl.uint<1>,
      in operand0: !firrtl.uint<${WIDTH}>,
      in operand1: !firrtl.uint<${WIDTH}>,
      in rd_en: !firrtl.uint<1>,
      out rd_data: !firrtl.uint<${WIDTH}>,
      out rd_ready: !firrtl.uint<1>,
      out input_ready: !firrtl.uint<1>
    ) attributes {defname = "${BASE_NAME}", annotations = ${ANNOTATIONS}}
EOF
    ;;
esac

cat >> "${MLIR_FILE}" << EOF
  }
}
EOF

# Generate filelist
generate_filelist "${FILELIST}" "${WRAPPER_FILE}" "${ALL_DEPS[@]}"

echo "Generated: ${MLIR_FILE}"
echo "Generated: ${FILELIST}"
