// Filelist for FloatSub_w32_l4
// Generated by build.sh (FloPoCo)

// Wrapper module
/home/xys/aps-mlir/circt/lib/Dialect/Cmt2/ModuleLibrary/firrtl/flopoco_ip/FloatSub.v

// FloPoCo dependencies
/home/xys/aps-mlir/flopoco-sv-lib/flopoco/IEEEFMA/IEEEFMA_S4.v
/home/xys/aps-mlir/flopoco-sv-lib/rtl/wrappers/IEEEFMA.sv
/home/xys/aps-mlir/flopoco-sv-lib/flopoco/IEEE2FP/IEEE2FP_S0.v
/home/xys/aps-mlir/flopoco-sv-lib/flopoco/FP2IEEE/FP2IEEE_S0.v
/home/xys/aps-mlir/flopoco-sv-lib/rtl/wrappers/IEEE2FP.sv
/home/xys/aps-mlir/flopoco-sv-lib/rtl/wrappers/FP2IEEE.sv
