// Filelist for Float2Int_w32_l2
// Generated by build.sh (FloPoCo)

// Wrapper module
/home/xys/aps-mlir/circt/lib/Dialect/Cmt2/ModuleLibrary/firrtl/flopoco_ip/Float2Int.v

// FloPoCo dependencies
/home/xys/aps-mlir/flopoco-sv-lib/flopoco/FP2Fix/FP2Fix_S1.v
/home/xys/aps-mlir/flopoco-sv-lib/rtl/wrappers/FP2INT.sv
/home/xys/aps-mlir/circt/lib/Dialect/Cmt2/ModuleLibrary/firrtl/fifo/fifo.sv
/home/xys/aps-mlir/flopoco-sv-lib/flopoco/IEEE2FP/IEEE2FP_S0.v
/home/xys/aps-mlir/flopoco-sv-lib/flopoco/FP2IEEE/FP2IEEE_S0.v
/home/xys/aps-mlir/flopoco-sv-lib/rtl/wrappers/IEEE2FP.sv
/home/xys/aps-mlir/flopoco-sv-lib/rtl/wrappers/FP2IEEE.sv
