// Generated by CIRCT e9b3f1e70
module GCD(
  input         clk,
                rst,
                load_enable,	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:44
  output        load_ready,	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:44
  input  [31:0] load_a,	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:44
                load_b,	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:44
  output        result_ready,	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:72
  output [31:0] result_res0	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:72
);

  wire [31:0] _GEN;	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:44, :54
  wire [31:0] _GEN_0;	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:44, :54
  wire [31:0] _reg_b_res0;
  wire [31:0] _reg_a_res0;
  FIRRTLReg_32 reg_a (
    .clk  (clk),
    .rst  (rst),
    .res0 (_reg_a_res0),
    .data (_GEN_0)	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:44, :54
  );
  wire [31:0] result_res0_0;	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:72
  assign result_res0_0 = _reg_a_res0;	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:72
  FIRRTLReg_32 reg_b (
    .clk  (clk),
    .rst  (rst),
    .res0 (_reg_b_res0),
    .data (_GEN)	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:44, :54
  );
  wire        _GEN_1 = (|_reg_b_res0) & ~(load_enable & 1'h1);	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:44, :54
  wire        _GEN_2 = _reg_a_res0 > _reg_b_res0;
  wire [32:0] _GEN_3 =
    _GEN_2 ? {1'h0, _reg_a_res0} - {1'h0, _reg_b_res0} : {1'h0, _reg_a_res0};
  wire [32:0] _GEN_4 =
    _GEN_2 ? {1'h0, _reg_b_res0} : {1'h0, _reg_b_res0} - {1'h0, _reg_a_res0};
  assign _GEN_0 = _GEN_1 ? _GEN_3[31:0] : load_a;	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:44, :54
  assign _GEN = _GEN_1 ? _GEN_4[31:0] : load_b;	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:44, :54
  assign load_ready = 1'h1;
  assign result_ready = _reg_b_res0 == 32'h0;
  assign result_res0 = result_res0_0;	// /home/uvxiao/circt-cmt2/examples/PyCMT2/test_gcd_simulation.py:72
endmodule

