// Generated by CIRCT e9b3f1e70
module Counter(
  input         clk,
                rst,
                start_enable,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:61
  output        start_ready,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:61
  input         stop_enable,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:70
  output        stop_ready,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:70
  input         reset_count_enable,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:78
  output        reset_count_ready,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:78
                get_count_ready,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:95
  output [31:0] get_count_res0,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:95
  output        is_running_ready,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:103
                is_running_res0	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:103
);

  wire [31:0] _GEN;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:78, :85
  wire        _GEN_0;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:61, :70
  wire        _running_res0;
  wire [31:0] _count_res0;
  FIRRTLReg_32 count (
    .clk  (clk),
    .rst  (rst),
    .res0 (_count_res0),
    .data (_GEN)	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:78, :85
  );
  wire [31:0] get_count_res0_0;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:95
  assign get_count_res0_0 = _count_res0;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:95
  FIRRTLReg_1 running (
    .clk  (clk),
    .rst  (rst),
    .res0 (_running_res0),
    .data (_GEN_0)	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:61, :70
  );
  wire        is_running_res0_0;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:103
  assign is_running_res0_0 = _running_res0;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:103
  wire        _GEN_1 = ~_running_res0;
  wire        _GEN_2 = _GEN_1 & start_enable;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:61
  wire        _GEN_3 = _running_res0 & ~_GEN_2;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:61, :70
  assign _GEN_0 = _GEN_3 & stop_enable ? 1'h0 : _GEN_2;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:61, :70
  wire [32:0] _GEN_4 = {1'h0, _count_res0} + 33'h1;
  assign _GEN = _running_res0 & ~(reset_count_enable & 1'h1) ? _GEN_4[31:0] : 32'h0;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:78, :85
  assign start_ready = _GEN_1;
  assign stop_ready = _GEN_3;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:70
  assign reset_count_ready = 1'h1;
  assign get_count_ready = 1'h1;
  assign get_count_res0 = get_count_res0_0;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:95
  assign is_running_ready = 1'h1;
  assign is_running_res0 = is_running_res0_0;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/simulation_workspace_example.py:103
endmodule

