// FIRRTLReg_32: Register with read/write interface
// Generated by pycmt2.stl
//
// This register updates unconditionally each cycle.
// Enable logic is handled externally by the CMT2->FIRRTL lowering.

module FIRRTLReg_32 (
    input  logic               clk,
    input  logic               rst,
    output logic [31:0] res0,
    input  logic [31:0] data
);
    logic [31:0] value;

    // Read output
    assign res0 = value;

    // Register update
    always_ff @(posedge clk) begin
        if (rst) begin
            value <= 32'h0;
        end else begin
            value <= data;
        end
    end

endmodule
