#  Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
#  See https://llvm.org/LICENSE.txt for license information.
#  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Standard Library (STL) module wrappers for PyCMT2.

This module provides Python wrappers for common hardware components
that can be instantiated in CMT2 designs. These match the C++ STLLibrary
bindings in lib/Dialect/Cmt2/ECMT2/STLLibrary.cpp.

Example:
    from pycmt2 import Circuit
    from pycmt2.stl import Reg

    circuit = Circuit("Counter")

    with circuit.module("Counter") as m:
        clk = m.clock()
        rst = m.reset()

        # Create a 32-bit register using STL
        reg_mod = Reg.create(circuit, 32)
        count = m.instance(reg_mod, "count", clk=clk, rst=rst)

        with m.rule("increment") as r:
            with r.guard() as g:
                g.always()
            with r.body() as body:
                val = body.call(count, "read")
                new_val = body.add(val, body.const(1, 32))
                body.call(count, "write", body.truncate(new_val, 32))
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from .types import UInt

if TYPE_CHECKING:
    from .circuit import Circuit
    from .external_module import ExternalModuleBuilder


# =============================================================================
# STL RTL Implementations (SystemVerilog)
# =============================================================================

# Registry of STL RTL implementations: module_name -> RTL content
_STL_RTL_REGISTRY: dict[str, str] = {}


def _generate_firrtl_reg_rtl(width: int) -> str:
    """Generate RTL for FIRRTLReg external module.

    The cmt2-to-firrtl pass generates register instances with:
    - clk, rst: clock and reset
    - res0: read output (value method result)
    - data: write input (method argument)

    The register unconditionally updates each cycle with the data input.
    The FIRRTL lowering handles enable logic externally via muxing.
    """
    return f"""\
// FIRRTLReg_{width}: Register with read/write interface
// Generated by pycmt2.stl
//
// This register updates unconditionally each cycle.
// Enable logic is handled externally by the CMT2->FIRRTL lowering.

module FIRRTLReg_{width} (
    input  logic               clk,
    input  logic               rst,
    output logic [{width-1}:0] res0,
    input  logic [{width-1}:0] data
);
    logic [{width-1}:0] value;

    // Read output
    assign res0 = value;

    // Register update
    always_ff @(posedge clk) begin
        if (rst) begin
            value <= {width}'h0;
        end else begin
            value <= data;
        end
    end

endmodule
"""


def _generate_wire_rtl(width: int) -> str:
    """Generate RTL for Wire external module.

    Similar to register but for combinational wires.
    The cmt2-to-firrtl pass generates wire instances with:
    - clk, rst: clock and reset
    - res0: read output
    - data: write input
    """
    return f"""\
// Wire_{width}: Wire with read/write interface
// Generated by pycmt2.stl
//
// This wire updates combinationally each cycle.

module Wire_{width} (
    input  logic               clk,
    input  logic               rst,
    output logic [{width-1}:0] res0,
    input  logic [{width-1}:0] data
);
    logic [{width-1}:0] value;

    // Read output
    assign res0 = value;

    // Wire update (each cycle)
    always_ff @(posedge clk) begin
        if (rst) begin
            value <= {width}'h0;
        end else begin
            value <= data;
        end
    end

endmodule
"""


# =============================================================================
# STL Component Factory Functions
# =============================================================================

class Reg:
    """Factory for register external modules.

    Creates an external module matching C++ STLLibrary::createRegModule:
    - clock port: "clk"
    - reset port: "rst"
    - value method: "read" -> returns data
    - action method: "write" <- takes data
    - sequence_before("read", "write")

    Example:
        reg_mod = Reg.create(circuit, 32)
        count = m.instance(reg_mod, "count", clk=clk, rst=rst)

        # In a rule body:
        val = body.call(count, "read")
        body.call(count, "write", val + body.const(1, 32))
    """

    @staticmethod
    def create(circuit: Circuit, width: int, init: int = 0) -> ExternalModuleBuilder:
        """Create a register external module.

        Args:
            circuit: The circuit to add the module to.
            width: Bit width of the register.
            init: Initial value (default 0).

        Returns:
            The ExternalModuleBuilder for the register.
        """
        # Use parameterized name to allow reuse
        name = f"FIRRTLReg_{width}"

        # Check if already exists
        if name in circuit._external_modules:
            return circuit._external_modules[name]

        # Create the external module
        with circuit.external_module(name) as reg:
            reg.clock("clk")
            reg.reset("rst")
            reg.value("read", returns=[UInt(width)])
            reg.method("write", args=[("data", UInt(width))])
            reg.sequence_before("read", "write")

        # Register RTL implementation
        _STL_RTL_REGISTRY[name] = _generate_firrtl_reg_rtl(width)

        return circuit._external_modules[name]

    @staticmethod
    def get_rtl(width: int) -> str:
        """Get the RTL implementation for a register of given width."""
        return _generate_firrtl_reg_rtl(width)


class Wire:
    """Factory for wire external modules.

    Creates an external module matching C++ STLLibrary::createWireModule:
    - clock port: "clk"
    - reset port: "rst"
    - value method: "read" -> returns data
    - action method: "write" <- takes data
    - sequence_before("write", "read")
    - conflict("write", "write")

    Example:
        wire_mod = Wire.create(circuit, 32)
        temp = m.instance(wire_mod, "temp", clk=clk, rst=rst)
    """

    @staticmethod
    def create(circuit: Circuit, width: int) -> ExternalModuleBuilder:
        """Create a wire external module.

        Args:
            circuit: The circuit to add the module to.
            width: Bit width of the wire.

        Returns:
            The ExternalModuleBuilder for the wire.
        """
        name = f"Wire_{width}"

        if name in circuit._external_modules:
            return circuit._external_modules[name]

        with circuit.external_module(name) as wire:
            wire.clock("clk")
            wire.reset("rst")
            wire.value("read", returns=[UInt(width)])
            wire.method("write", args=[("data", UInt(width))])
            wire.conflict("write", "write")
            wire.sequence_before("write", "read")

        _STL_RTL_REGISTRY[name] = _generate_wire_rtl(width)

        return circuit._external_modules[name]

    @staticmethod
    def get_rtl(width: int) -> str:
        """Get the RTL implementation for a wire of given width."""
        return _generate_wire_rtl(width)


# =============================================================================
# STL Integration with SimulationWorkspace
# =============================================================================

def get_stl_rtl_files() -> dict[str, str]:
    """Get all registered STL RTL implementations.

    Returns:
        Dictionary of filename -> RTL content for all used STL modules.
    """
    result = {}
    for name, content in _STL_RTL_REGISTRY.items():
        result[f"{name}.sv"] = content
    return result


def add_stl_rtl_to_workspace(workspace) -> None:
    """Add all registered STL RTL files to a simulation workspace.

    This should be called after the circuit is built but before
    generating the workspace.

    Args:
        workspace: SimulationWorkspace instance.
    """
    for filename, content in get_stl_rtl_files().items():
        workspace.add_external_rtl(filename, content)


def clear_stl_registry() -> None:
    """Clear the STL RTL registry.

    Useful for tests or when building multiple independent circuits.
    """
    _STL_RTL_REGISTRY.clear()


# =============================================================================
# Placeholder classes for future implementation
# =============================================================================

class FIFO:
    """Factory for FIFO external modules (placeholder).

    TODO: Implement FIFO1_PUSH, FIFO1_PULL, FIFO2_I as in C++ STLLibrary.
    """

    @staticmethod
    def create(circuit: Circuit, width: int, depth: int = 1) -> ExternalModuleBuilder:
        """Create a FIFO external module."""
        raise NotImplementedError(
            "FIFO.create() is not yet implemented. "
            "Use circuit.external_module() to define your own FIFO."
        )


class Memory:
    """Factory for Memory external modules (placeholder).

    TODO: Implement Mem1r1w as in C++ STLLibrary.
    """

    @staticmethod
    def create(
        circuit: Circuit,
        data_width: int,
        addr_width: int,
        depth: int,
    ) -> ExternalModuleBuilder:
        """Create a memory external module."""
        raise NotImplementedError(
            "Memory.create() is not yet implemented. "
            "Use circuit.external_module() to define your own Memory."
        )
