#  Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
#  See https://llvm.org/LICENSE.txt for license information.
#  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Standard Library (STL) module wrappers for PyCMT2.

This module provides Python wrappers for common hardware components
that can be instantiated in CMT2 designs. These match the C++ STLLibrary
bindings in lib/Dialect/Cmt2/ECMT2/STLLibrary.cpp.

Example:
    from pycmt2 import Circuit
    from pycmt2.stl import Reg

    circuit = Circuit("Counter")

    with circuit.module("Counter") as m:
        clk = m.clock()
        rst = m.reset()

        # Create a 32-bit register using STL
        reg_mod = Reg.create(circuit, 32)
        count = m.instance(reg_mod, "count", clk=clk, rst=rst)

        with m.rule("increment") as r:
            with r.guard() as g:
                g.always()
            with r.body() as body:
                val = body.call(count, "read")
                new_val = body.add(val, body.const(1, 32))
                body.call(count, "write", body.truncate(new_val, 32))
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from .types import UInt

if TYPE_CHECKING:
    from .circuit import Circuit
    from .external_module import ExternalModuleBuilder


# =============================================================================
# STL RTL Implementations (SystemVerilog)
# =============================================================================

# Registry of STL RTL implementations: module_name -> RTL content
_STL_RTL_REGISTRY: dict[str, str] = {}


def _generate_firrtl_reg_rtl(width: int) -> str:
    """Generate RTL for FIRRTLReg external module.

    Port names match ECMT2 STLLibrary::createRegModule:
    - clk, rst: clock and reset
    - read_ready: ready output for read value (always 1)
    - read_data: read output data
    - write_enable: enable input for write method
    - write_ready: ready output for write method (always 1)
    - write_data: write input data

    The register updates when write_enable is high.
    """
    return f"""\
// FIRRTLReg_{width}: Register with read/write interface
// Generated by pycmt2.stl
//
// Matches ECMT2 STLLibrary::createRegModule port naming.

module FIRRTLReg_{width} (
    input  logic               clk,
    input  logic               rst,
    // read value method
    output logic               read_ready,
    output logic [{width-1}:0] read_data,
    // write action method
    input  logic               write_enable,
    output logic               write_ready,
    input  logic [{width-1}:0] write_data
);
    logic [{width-1}:0] value;

    // Read is always ready
    assign read_ready = 1'b1;
    assign read_data = value;

    // Write is always ready
    assign write_ready = 1'b1;

    // Register update on write_enable
    always_ff @(posedge clk) begin
        if (rst) begin
            value <= {width}'h0;
        end else if (write_enable) begin
            value <= write_data;
        end
    end

endmodule
"""


def _generate_wire_rtl(width: int) -> str:
    """Generate RTL for Wire external module.

    Port names match ECMT2 STLLibrary::createWireModule:
    - clk, rst: clock and reset
    - read_ready: ready output for read value (always 1)
    - read_data: read output data
    - write_enable: enable input for write method
    - write_ready: ready output for write method (always 1)
    - write_data: write input data

    Wire updates when write_enable is high (like register but for combinational use).
    """
    return f"""\
// Wire_{width}: Wire with read/write interface
// Generated by pycmt2.stl
//
// Matches ECMT2 STLLibrary::createWireModule port naming.

module Wire_{width} (
    input  logic               clk,
    input  logic               rst,
    // read value method
    output logic               read_ready,
    output logic [{width-1}:0] read_data,
    // write action method
    input  logic               write_enable,
    output logic               write_ready,
    input  logic [{width-1}:0] write_data
);
    logic [{width-1}:0] value;

    // Read is always ready
    assign read_ready = 1'b1;
    assign read_data = value;

    // Write is always ready
    assign write_ready = 1'b1;

    // Wire update on write_enable
    always_ff @(posedge clk) begin
        if (rst) begin
            value <= {width}'h0;
        end else if (write_enable) begin
            value <= write_data;
        end
    end

endmodule
"""


# =============================================================================
# STL Component Factory Functions
# =============================================================================

class Reg:
    """Factory for register external modules.

    Creates an external module matching C++ STLLibrary::createRegModule:
    - clock port: "clk"
    - reset port: "rst"
    - value method: "read" -> returns data
    - action method: "write" <- takes data
    - sequence_before("read", "write")

    Example:
        reg_mod = Reg.create(circuit, 32)
        count = m.instance(reg_mod, "count", clk=clk, rst=rst)

        # In a rule body:
        val = body.call(count, "read")
        body.call(count, "write", val + body.const(1, 32))
    """

    @staticmethod
    def create(circuit: Circuit, width: int, init: int = 0) -> ExternalModuleBuilder:
        """Create a register external module.

        Args:
            circuit: The circuit to add the module to.
            width: Bit width of the register.
            init: Initial value (default 0).

        Returns:
            The ExternalModuleBuilder for the register.
        """
        # Use parameterized name to allow reuse
        name = f"FIRRTLReg_{width}"

        # Check if already exists
        if name in circuit._external_modules:
            return circuit._external_modules[name]

        # Create the external module matching ECMT2 STLLibrary::createRegModule
        with circuit.external_module(name) as reg:
            reg.clock("clk")
            reg.reset("rst")
            reg.value("read",
                      ready_name="read_ready",
                      returns=[("read_data", UInt(width))])
            reg.method("write",
                       enable_name="write_enable",
                       ready_name="write_ready",
                       args=[("write_data", UInt(width))])
            reg.sequence_before("read", "write")

        # Register RTL implementation
        _STL_RTL_REGISTRY[name] = _generate_firrtl_reg_rtl(width)

        return circuit._external_modules[name]

    @staticmethod
    def get_rtl(width: int) -> str:
        """Get the RTL implementation for a register of given width."""
        return _generate_firrtl_reg_rtl(width)


class Wire:
    """Factory for wire external modules.

    Creates an external module matching C++ STLLibrary::createWireModule:
    - clock port: "clk"
    - reset port: "rst"
    - value method: "read" -> returns data
    - action method: "write" <- takes data
    - sequence_before("write", "read")
    - conflict("write", "write")

    Example:
        wire_mod = Wire.create(circuit, 32)
        temp = m.instance(wire_mod, "temp", clk=clk, rst=rst)
    """

    @staticmethod
    def create(circuit: Circuit, width: int) -> ExternalModuleBuilder:
        """Create a wire external module.

        Args:
            circuit: The circuit to add the module to.
            width: Bit width of the wire.

        Returns:
            The ExternalModuleBuilder for the wire.
        """
        name = f"Wire_{width}"

        if name in circuit._external_modules:
            return circuit._external_modules[name]

        # Create the external module matching ECMT2 STLLibrary::createWireModule
        with circuit.external_module(name) as wire:
            wire.clock("clk")
            wire.reset("rst")
            wire.value("read",
                       ready_name="read_ready",
                       returns=[("read_data", UInt(width))])
            wire.method("write",
                        enable_name="write_enable",
                        ready_name="write_ready",
                        args=[("write_data", UInt(width))])
            wire.conflict("write", "write")
            wire.sequence_before("write", "read")

        _STL_RTL_REGISTRY[name] = _generate_wire_rtl(width)

        return circuit._external_modules[name]

    @staticmethod
    def get_rtl(width: int) -> str:
        """Get the RTL implementation for a wire of given width."""
        return _generate_wire_rtl(width)


# =============================================================================
# STL Integration with SimulationWorkspace
# =============================================================================

def get_stl_rtl_files() -> dict[str, str]:
    """Get all registered STL RTL implementations.

    Returns:
        Dictionary of filename -> RTL content for all used STL modules.
    """
    result = {}
    for name, content in _STL_RTL_REGISTRY.items():
        result[f"{name}.sv"] = content
    return result


def add_stl_rtl_to_workspace(workspace) -> None:
    """Add all registered STL RTL files to a simulation workspace.

    This should be called after the circuit is built but before
    generating the workspace.

    Args:
        workspace: SimulationWorkspace instance.
    """
    for filename, content in get_stl_rtl_files().items():
        workspace.add_external_rtl(filename, content)


def clear_stl_registry() -> None:
    """Clear the STL RTL registry.

    Useful for tests or when building multiple independent circuits.
    """
    _STL_RTL_REGISTRY.clear()


# =============================================================================
# FIFO Variants (matching ECMT2 STLLibrary)
# =============================================================================
#
# The ECMT2 STL provides three FIFO variants:
# 1. FIFO1_PUSH - Depth-1, actively push (enq guarded, deq always ready when full)
# 2. FIFO1_PULL - Depth-1, actively pull (enq always ready, deq guarded)
# 3. FIFO2_I    - Depth-2 with independent enq/deq (state machine)
#
# These are implemented as external modules with RTL generation.
# =============================================================================


def _generate_fifo1_push_rtl(width: int) -> str:
    """Generate RTL for FIFO1_PUSH module.

    Interface:
    - full_res0: output, 1 when FIFO is full
    - deq_enable: input, assert to dequeue
    - deq_res0: output, dequeued data
    - deq_ready: output, 1 when can dequeue (full)
    - enq_enable: input, assert to enqueue
    - enq_data: input, data to enqueue
    - enq_ready: output, 1 when can enqueue (!full | deqed)
    """
    return f"""\
// FIFO1_PUSH_{width}: Depth-1 FIFO with active push semantics
// Generated by pycmt2.stl
//
// Push semantics: enq is guarded (!full | concurrent_deq), deq ready when full

module FIFO1_PUSH_{width} (
    input  logic               clk,
    input  logic               rst,
    // full value
    output logic               full_res0,
    output logic               full_ready,
    // deq method
    input  logic               deq_enable,
    output logic [{width-1}:0] deq_res0,
    output logic               deq_ready,
    // enq method
    input  logic               enq_enable,
    input  logic [{width-1}:0] enq_data,
    output logic               enq_ready
);
    // Storage
    logic [{width-1}:0] data_reg;
    logic full_reg;

    // Output assignments
    assign full_res0 = full_reg;
    assign full_ready = 1'b1;
    assign deq_res0 = data_reg;
    assign deq_ready = full_reg;  // Can deq when full
    assign enq_ready = ~full_reg | deq_enable;  // Can enq when not full or concurrent deq

    // State update
    always_ff @(posedge clk) begin
        if (rst) begin
            data_reg <= {width}'h0;
            full_reg <= 1'b0;
        end else begin
            // Update data on enqueue
            if (enq_enable && enq_ready) begin
                data_reg <= enq_data;
            end
            // Update full: full = enqed | (full & !deqed)
            full_reg <= (enq_enable && enq_ready) |
                        (full_reg && !(deq_enable && deq_ready));
        end
    end

endmodule
"""


def _generate_fifo1_pull_rtl(width: int) -> str:
    """Generate RTL for FIFO1_PULL module.

    Interface similar to PUSH but with different guard semantics:
    - enq always ready (overwrites)
    - deq guarded by (full & concurrent_enq)
    """
    return f"""\
// FIFO1_PULL_{width}: Depth-1 FIFO with active pull semantics
// Generated by pycmt2.stl
//
// Pull semantics: enq always ready, deq guarded by (full & enqed)

module FIFO1_PULL_{width} (
    input  logic               clk,
    input  logic               rst,
    // full value
    output logic               full_res0,
    output logic               full_ready,
    // enq method
    input  logic               enq_enable,
    input  logic [{width-1}:0] enq_data,
    output logic               enq_ready,
    // deq value (returns data when ready)
    output logic [{width-1}:0] deq_res0,
    output logic               deq_ready
);
    // Storage
    logic [{width-1}:0] data_reg;
    logic full_reg;

    // Output assignments
    assign full_res0 = full_reg;
    assign full_ready = 1'b1;
    assign enq_ready = 1'b1;  // Always ready to enqueue (overwrites)
    assign deq_res0 = data_reg;
    assign deq_ready = full_reg && enq_enable;  // Can deq when full AND concurrent enq

    // State update
    always_ff @(posedge clk) begin
        if (rst) begin
            data_reg <= {width}'h0;
            full_reg <= 1'b0;
        end else begin
            // Update data on enqueue
            if (enq_enable) begin
                data_reg <= enq_data;
            end
            // Update full: full = enqed | (full & !deqed)
            full_reg <= enq_enable | (full_reg && !deq_ready);
        end
    end

endmodule
"""


def _generate_fifo2_i_rtl(width: int) -> str:
    """Generate RTL for FIFO2_I module.

    Depth-2 FIFO with independent enq/deq:
    - State: 0=empty, 1=one element, 2=full
    - Can enq and deq in same cycle
    """
    return f"""\
// FIFO2_I_{width}: Depth-2 FIFO with independent enq/deq
// Generated by pycmt2.stl
//
// State machine: 0=empty, 1=one element, 2=full
// Allows concurrent enq and deq

module FIFO2_I_{width} (
    input  logic               clk,
    input  logic               rst,
    // full value - true when FIFO is at capacity (state == 2)
    output logic               full_res0,
    output logic               full_ready,
    // notEmpty value - true when FIFO has data (state != 0)
    output logic               notEmpty_res0,
    output logic               notEmpty_ready,
    // deq method
    input  logic               deq_enable,
    output logic [{width-1}:0] deq_res0,
    output logic               deq_ready,
    // enq method
    input  logic               enq_enable,
    input  logic [{width-1}:0] enq_data,
    output logic               enq_ready
);
    // Storage: two registers for double buffering
    logic [{width-1}:0] reg0, reg1;
    logic [1:0] state;  // 0=empty, 1=one, 2=full

    // Output assignments
    assign full_res0 = (state == 2'd2);
    assign full_ready = 1'b1;
    assign notEmpty_res0 = (state != 2'd0);
    assign notEmpty_ready = 1'b1;
    assign deq_res0 = reg0;
    assign deq_ready = (state != 2'd0);  // Can deq when not empty
    assign enq_ready = (state != 2'd2);  // Can enq when not full

    // Actual operations this cycle
    wire do_enq = enq_enable && enq_ready;
    wire do_deq = deq_enable && deq_ready;

    // State update
    always_ff @(posedge clk) begin
        if (rst) begin
            reg0 <= {width}'h0;
            reg1 <= {width}'h0;
            state <= 2'd0;
        end else begin
            case (state)
                2'd0: begin  // Empty
                    if (do_enq) begin
                        reg0 <= enq_data;
                        state <= 2'd1;
                    end
                end
                2'd1: begin  // One element
                    if (do_enq && do_deq) begin
                        // Replace reg0
                        reg0 <= enq_data;
                        // Stay at state 1
                    end else if (do_enq) begin
                        // Shift reg0 to reg1, put new data in reg0
                        reg1 <= reg0;
                        reg0 <= enq_data;
                        state <= 2'd2;
                    end else if (do_deq) begin
                        // Go to empty
                        state <= 2'd0;
                    end
                end
                2'd2: begin  // Full
                    if (do_deq) begin
                        // Shift reg1 to reg0
                        reg0 <= reg1;
                        state <= 2'd1;
                    end
                end
                default: state <= 2'd0;
            endcase
        end
    end

endmodule
"""


class FIFO1Push:
    """Factory for depth-1 FIFO with active push semantics.

    Matches ECMT2 STLLibrary::createFIFO1PushModule.

    Interface:
    - value "full" -> bool: Returns true when FIFO is full
    - method "deq" -> data: Dequeue data (guard: full)
    - method "enq" (data): Enqueue data (guard: !full | deqed)

    The "push" semantics means:
    - Producer (enq) is guarded by FIFO state
    - Consumer (deq) can always dequeue when data is available

    Example:
        fifo_mod = FIFO1Push.create(circuit, 32)
        fifo = m.instance(fifo_mod, "input_fifo", clk=clk, rst=rst)
    """

    @staticmethod
    def create(circuit: Circuit, width: int):
        """Create a depth-1 push-style FIFO."""
        name = f"FIFO1_PUSH_{width}"

        if name in circuit._external_modules:
            return circuit._external_modules[name]

        with circuit.external_module(name) as fifo:
            fifo.clock("clk")
            fifo.reset("rst")
            # Value: full
            fifo.value("full", returns=[UInt(1)])
            # Method: deq (returns data)
            fifo.method("deq", returns=[UInt(width)])
            # Method: enq (takes data)
            fifo.method("enq", args=[("data", UInt(width))])
            # Sequencing: full < deq < enq
            fifo.sequence_before("full", "deq")
            fifo.sequence_before("deq", "enq")

        _STL_RTL_REGISTRY[name] = _generate_fifo1_push_rtl(width)

        return circuit._external_modules[name]


class FIFO1Pull:
    """Factory for depth-1 FIFO with active pull semantics.

    Matches ECMT2 STLLibrary::createFIFO1PullModule.

    Interface:
    - value "full" -> bool: Returns true when FIFO is full
    - method "enq" (data): Enqueue data (always ready)
    - value "deq" -> data: Dequeue data (guard: full & enqed)

    The "pull" semantics means:
    - Producer (enq) can always enqueue
    - Consumer (deq) is guarded by data availability

    Example:
        fifo_mod = FIFO1Pull.create(circuit, 32)
        fifo = m.instance(fifo_mod, "output_fifo", clk=clk, rst=rst)
    """

    @staticmethod
    def create(circuit: Circuit, width: int):
        """Create a depth-1 pull-style FIFO."""
        name = f"FIFO1_PULL_{width}"

        if name in circuit._external_modules:
            return circuit._external_modules[name]

        with circuit.external_module(name) as fifo:
            fifo.clock("clk")
            fifo.reset("rst")
            # Value: full
            fifo.value("full", returns=[UInt(1)])
            # Method: enq
            fifo.method("enq", args=[("data", UInt(width))])
            # Value: deq (returns data)
            fifo.value("deq", returns=[UInt(width)])
            # Sequencing: full < enq < deq
            fifo.sequence_before("full", "enq")
            fifo.sequence_before("enq", "deq")

        _STL_RTL_REGISTRY[name] = _generate_fifo1_pull_rtl(width)

        return circuit._external_modules[name]


class FIFO2I:
    """Factory for depth-2 FIFO with independent enq/deq.

    Matches ECMT2 STLLibrary::createFIFO2IModule.

    Interface:
    - value "full" -> bool: Returns true when state == 2 (FIFO at capacity)
    - value "notEmpty" -> bool: Returns true when state != 0 (FIFO has data)
    - method "deq" -> data: Dequeue data (guard: state != 0)
    - method "enq" (data): Enqueue data (guard: state != 2)

    This FIFO allows independent enq and deq in the same cycle.

    Example:
        fifo_mod = FIFO2I.create(circuit, 32)
        fifo = m.instance(fifo_mod, "buffer", clk=clk, rst=rst)

        # In a rule guard:
        has_data = g.call(fifo, "notEmpty")  # Check if FIFO has data
        not_full = g.not_(g.call(fifo, "full"))  # Check if FIFO can accept data
    """

    @staticmethod
    def create(circuit: Circuit, width: int):
        """Create a depth-2 independent FIFO."""
        name = f"FIFO2_I_{width}"

        if name in circuit._external_modules:
            return circuit._external_modules[name]

        with circuit.external_module(name) as fifo:
            fifo.clock("clk")
            fifo.reset("rst")
            # Value: full - returns true when FIFO is at capacity
            fifo.value("full",
                       ready_name="full_ready",
                       returns=[("full_res0", UInt(1))])
            # Value: notEmpty - returns true when FIFO has data
            fifo.value("notEmpty",
                       ready_name="notEmpty_ready",
                       returns=[("notEmpty_res0", UInt(1))])
            # Method: deq - returns dequeued data
            fifo.method("deq",
                        enable_name="deq_enable",
                        ready_name="deq_ready",
                        returns=[("deq_res0", UInt(width))])
            # Method: enq - takes data to enqueue
            fifo.method("enq",
                        enable_name="enq_enable",
                        ready_name="enq_ready",
                        args=[("enq_data", UInt(width))])
            # Sequencing: values < deq < enq
            fifo.sequence_before("full", "deq")
            fifo.sequence_before("deq", "enq")

        _STL_RTL_REGISTRY[name] = _generate_fifo2_i_rtl(width)

        return circuit._external_modules[name]


class FIFO:
    """Factory for FIFO modules.

    For specific FIFO variants, use:
    - FIFO1Push: Depth-1 with active push semantics
    - FIFO1Pull: Depth-1 with active pull semantics
    - FIFO2I: Depth-2 with independent enq/deq

    Example:
        fifo_mod = FIFO.create(circuit, 32)
        fifo = m.instance(fifo_mod, "data_fifo", clk=clk, rst=rst)
    """

    @staticmethod
    def create(circuit: Circuit, width: int, depth: int = 2):
        """Create a FIFO external module.

        Args:
            circuit: The circuit to add the module to.
            width: Bit width of the data.
            depth: FIFO depth (1 or 2, default 2).

        Returns:
            The ExternalModuleBuilder for the FIFO.
        """
        if depth == 1:
            return FIFO1Push.create(circuit, width)
        else:
            return FIFO2I.create(circuit, width)


class Memory:
    """Factory for Memory external modules (placeholder).

    TODO: Implement Mem1r1w as in C++ STLLibrary.
    """

    @staticmethod
    def create(
        circuit: Circuit,
        data_width: int,
        addr_width: int,
        depth: int,
    ) -> ExternalModuleBuilder:
        """Create a memory external module."""
        raise NotImplementedError(
            "Memory.create() is not yet implemented. "
            "Use circuit.external_module() to define your own Memory."
        )
