#!/bin/bash
#===- build.sh - Build script for Float IP modules --------------*- Bash -*-===#
#
# Generates FIRRTL extmodule declarations for HardFloat-based floating-point IPs
# Also generates filelist.f for synthesis tools
#
# Parameters:
#   op       - Operation type: add, sub, mul, div, sqrt, cmp
#   width    - Data width (16, 32, 64)
#   latency  - Pipeline latency
#   predicate - For cmp only: 0=eq, 1=lt, 2=le, 3=gt, 4=ge, 5=ne, 6=ord, 7=uno
#
# Outputs:
#   <module_name>.mlir  - FIRRTL extmodule with BlackBoxPathAnno
#   <module_name>.f     - Filelist for synthesis tools
#
#===------------------------------------------------------------------------===#

set -e

# Default parameters
OP="add"
WIDTH=32
LATENCY=1
PREDICATE=0

# Parse named parameters
for arg in "$@"; do
  case $arg in
    op=*)
      OP="${arg#*=}"
      ;;
    width=*)
      WIDTH="${arg#*=}"
      ;;
    latency=*)
      LATENCY="${arg#*=}"
      ;;
    predicate=*)
      PREDICATE="${arg#*=}"
      ;;
    *)
      echo "Unknown parameter: $arg" >&2
      ;;
  esac
done

# Get script directory for Verilog file paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# HardFloat source directory (relative to aps-mlir root)
HARDFLOAT_DIR="$(cd "${SCRIPT_DIR}/../../../../../../../HardFloat/source" 2>/dev/null && pwd)" 

# Common HardFloat dependencies
COMMON_DEPS=(
  "${HARDFLOAT_DIR}/HardFloat_primitives.v"
  "${HARDFLOAT_DIR}/HardFloat_rawFN.v"
  "${HARDFLOAT_DIR}/isSigNaNRecFN.v"
  "${HARDFLOAT_DIR}/fNToRecFN.v"
  "${HARDFLOAT_DIR}/recFNToFN.v"
)

# Function to generate BlackBoxPathAnno array
generate_annotations() {
  local wrapper_file="$1"
  shift
  local deps=("$@")

  local annos="{class = \"firrtl.transforms.BlackBoxPathAnno\", path = \"${wrapper_file}\"}"
  for dep in "${deps[@]}"; do
    annos="${annos}, {class = \"firrtl.transforms.BlackBoxPathAnno\", path = \"${dep}\"}"
  done
  echo "[${annos}]"
}

# Function to generate filelist
generate_filelist() {
  local filelist="$1"
  local wrapper_file="$2"
  shift 2
  local deps=("$@")

  {
    echo "// Filelist for ${MODULE_NAME}"
    echo "// Generated by build.sh"
    echo ""
    echo "// Wrapper module"
    echo "${wrapper_file}"
    echo ""
    echo "// HardFloat dependencies"
    for dep in "${deps[@]}"; do
      echo "${dep}"
    done
  } > "${filelist}"
}

# Generate module name and output file based on operation
case $OP in
  add)
    MODULE_NAME="FloatAdd_w${WIDTH}_l${LATENCY}"
    VERILOG_FILE="${SCRIPT_DIR}/FloatAdd.v"
    OUTPUT_FILE="${MODULE_NAME}.mlir"
    FILELIST="${MODULE_NAME}.f"
    DEFNAME="FloatAdd"

    # Add-specific dependencies
    OP_DEPS=(
      "${HARDFLOAT_DIR}/addRecFN.v"
    )
    ALL_DEPS=("${COMMON_DEPS[@]}" "${OP_DEPS[@]}")
    ANNOTATIONS=$(generate_annotations "${VERILOG_FILE}" "${ALL_DEPS[@]}")

    cat > "$OUTPUT_FILE" << EOF
module {
  firrtl.circuit "${MODULE_NAME}" {
    firrtl.extmodule @${MODULE_NAME}<WIDTH: i64 = ${WIDTH}, LATENCY: i64 = ${LATENCY}>(
      in clock: !firrtl.clock,
      in reset: !firrtl.uint<1>,
      in ce: !firrtl.uint<1>,
      in operand0: !firrtl.uint<${WIDTH}>,
      in operand1: !firrtl.uint<${WIDTH}>,
      out result: !firrtl.uint<${WIDTH}>,
      out valid: !firrtl.uint<1>,
      out input_ready: !firrtl.uint<1>
    ) attributes {defname = "${DEFNAME}", annotations = ${ANNOTATIONS}}
  }
}
EOF
    generate_filelist "${FILELIST}" "${VERILOG_FILE}" "${ALL_DEPS[@]}"
    ;;

  sub)
    MODULE_NAME="FloatSub_w${WIDTH}_l${LATENCY}"
    VERILOG_FILE="${SCRIPT_DIR}/FloatSub.v"
    OUTPUT_FILE="${MODULE_NAME}.mlir"
    FILELIST="${MODULE_NAME}.f"
    DEFNAME="FloatSub"

    # Sub uses addRecFN with subOp=1
    OP_DEPS=(
      "${HARDFLOAT_DIR}/addRecFN.v"
    )
    ALL_DEPS=("${COMMON_DEPS[@]}" "${OP_DEPS[@]}")
    ANNOTATIONS=$(generate_annotations "${VERILOG_FILE}" "${ALL_DEPS[@]}")

    cat > "$OUTPUT_FILE" << EOF
module {
  firrtl.circuit "${MODULE_NAME}" {
    firrtl.extmodule @${MODULE_NAME}<WIDTH: i64 = ${WIDTH}, LATENCY: i64 = ${LATENCY}>(
      in clock: !firrtl.clock,
      in reset: !firrtl.uint<1>,
      in ce: !firrtl.uint<1>,
      in operand0: !firrtl.uint<${WIDTH}>,
      in operand1: !firrtl.uint<${WIDTH}>,
      out result: !firrtl.uint<${WIDTH}>,
      out valid: !firrtl.uint<1>,
      out input_ready: !firrtl.uint<1>
    ) attributes {defname = "${DEFNAME}", annotations = ${ANNOTATIONS}}
  }
}
EOF
    generate_filelist "${FILELIST}" "${VERILOG_FILE}" "${ALL_DEPS[@]}"
    ;;

  mul)
    MODULE_NAME="FloatMul_w${WIDTH}_l${LATENCY}"
    VERILOG_FILE="${SCRIPT_DIR}/FloatMul.v"
    OUTPUT_FILE="${MODULE_NAME}.mlir"
    FILELIST="${MODULE_NAME}.f"
    DEFNAME="FloatMul"

    # Mul-specific dependencies
    OP_DEPS=(
      "${HARDFLOAT_DIR}/mulRecFN.v"
    )
    ALL_DEPS=("${COMMON_DEPS[@]}" "${OP_DEPS[@]}")
    ANNOTATIONS=$(generate_annotations "${VERILOG_FILE}" "${ALL_DEPS[@]}")

    cat > "$OUTPUT_FILE" << EOF
module {
  firrtl.circuit "${MODULE_NAME}" {
    firrtl.extmodule @${MODULE_NAME}<WIDTH: i64 = ${WIDTH}, LATENCY: i64 = ${LATENCY}>(
      in clock: !firrtl.clock,
      in reset: !firrtl.uint<1>,
      in ce: !firrtl.uint<1>,
      in operand0: !firrtl.uint<${WIDTH}>,
      in operand1: !firrtl.uint<${WIDTH}>,
      out result: !firrtl.uint<${WIDTH}>,
      out valid: !firrtl.uint<1>,
      out input_ready: !firrtl.uint<1>
    ) attributes {defname = "${DEFNAME}", annotations = ${ANNOTATIONS}}
  }
}
EOF
    generate_filelist "${FILELIST}" "${VERILOG_FILE}" "${ALL_DEPS[@]}"
    ;;

  div)
    MODULE_NAME="FloatDiv_w${WIDTH}_l${LATENCY}"
    VERILOG_FILE="${SCRIPT_DIR}/FloatDiv.v"
    OUTPUT_FILE="${MODULE_NAME}.mlir"
    FILELIST="${MODULE_NAME}.f"
    DEFNAME="FloatDiv"

    # Div uses divSqrtRecFN_small
    OP_DEPS=(
      "${HARDFLOAT_DIR}/divSqrtRecFN_small.v"
    )
    ALL_DEPS=("${COMMON_DEPS[@]}" "${OP_DEPS[@]}")
    ANNOTATIONS=$(generate_annotations "${VERILOG_FILE}" "${ALL_DEPS[@]}")

    cat > "$OUTPUT_FILE" << EOF
module {
  firrtl.circuit "${MODULE_NAME}" {
    firrtl.extmodule @${MODULE_NAME}<WIDTH: i64 = ${WIDTH}, LATENCY: i64 = ${LATENCY}>(
      in clock: !firrtl.clock,
      in reset: !firrtl.uint<1>,
      in ce: !firrtl.uint<1>,
      in operand0: !firrtl.uint<${WIDTH}>,
      in operand1: !firrtl.uint<${WIDTH}>,
      out result: !firrtl.uint<${WIDTH}>,
      out valid: !firrtl.uint<1>,
      out input_ready: !firrtl.uint<1>
    ) attributes {defname = "${DEFNAME}", annotations = ${ANNOTATIONS}}
  }
}
EOF
    generate_filelist "${FILELIST}" "${VERILOG_FILE}" "${ALL_DEPS[@]}"
    ;;

  sqrt)
    MODULE_NAME="FloatSqrt_w${WIDTH}_l${LATENCY}"
    VERILOG_FILE="${SCRIPT_DIR}/FloatSqrt.v"
    OUTPUT_FILE="${MODULE_NAME}.mlir"
    FILELIST="${MODULE_NAME}.f"
    DEFNAME="FloatSqrt"

    # Sqrt uses divSqrtRecFN_small
    OP_DEPS=(
      "${HARDFLOAT_DIR}/divSqrtRecFN_small.v"
    )
    ALL_DEPS=("${COMMON_DEPS[@]}" "${OP_DEPS[@]}")
    ANNOTATIONS=$(generate_annotations "${VERILOG_FILE}" "${ALL_DEPS[@]}")

    cat > "$OUTPUT_FILE" << EOF
module {
  firrtl.circuit "${MODULE_NAME}" {
    firrtl.extmodule @${MODULE_NAME}<WIDTH: i64 = ${WIDTH}, LATENCY: i64 = ${LATENCY}>(
      in clock: !firrtl.clock,
      in reset: !firrtl.uint<1>,
      in ce: !firrtl.uint<1>,
      in operand0: !firrtl.uint<${WIDTH}>,
      out result: !firrtl.uint<${WIDTH}>,
      out valid: !firrtl.uint<1>,
      out input_ready: !firrtl.uint<1>
    ) attributes {defname = "${DEFNAME}", annotations = ${ANNOTATIONS}}
  }
}
EOF
    generate_filelist "${FILELIST}" "${VERILOG_FILE}" "${ALL_DEPS[@]}"
    ;;

  cmp)
    MODULE_NAME="FloatCmp_w${WIDTH}_p${PREDICATE}_l${LATENCY}"
    VERILOG_FILE="${SCRIPT_DIR}/FloatCmp.v"
    OUTPUT_FILE="${MODULE_NAME}.mlir"
    FILELIST="${MODULE_NAME}.f"
    DEFNAME="FloatCmp"

    # Cmp-specific dependencies (no recFNToFN needed, output is 1-bit)
    CMP_DEPS=(
      "${HARDFLOAT_DIR}/HardFloat_primitives.v"
      "${HARDFLOAT_DIR}/HardFloat_rawFN.v"
      "${HARDFLOAT_DIR}/isSigNaNRecFN.v"
      "${HARDFLOAT_DIR}/fNToRecFN.v"
      "${HARDFLOAT_DIR}/compareRecFN.v"
    )
    ANNOTATIONS=$(generate_annotations "${VERILOG_FILE}" "${CMP_DEPS[@]}")

    cat > "$OUTPUT_FILE" << EOF
module {
  firrtl.circuit "${MODULE_NAME}" {
    firrtl.extmodule @${MODULE_NAME}<WIDTH: i64 = ${WIDTH}, PREDICATE: i64 = ${PREDICATE}, LATENCY: i64 = ${LATENCY}>(
      in clock: !firrtl.clock,
      in reset: !firrtl.uint<1>,
      in ce: !firrtl.uint<1>,
      in operand0: !firrtl.uint<${WIDTH}>,
      in operand1: !firrtl.uint<${WIDTH}>,
      out result: !firrtl.uint<1>,
      out valid: !firrtl.uint<1>,
      out input_ready: !firrtl.uint<1>
    ) attributes {defname = "${DEFNAME}", annotations = ${ANNOTATIONS}}
  }
}
EOF
    generate_filelist "${FILELIST}" "${VERILOG_FILE}" "${CMP_DEPS[@]}"
    ;;

  *)
    echo "Error: Unknown operation '$OP'. Valid operations: add, sub, mul, div, sqrt, cmp" >&2
    exit 1
    ;;
esac

echo "Generated: ${OUTPUT_FILE}, ${FILELIST}"
