// Filelist for FloatAdd_w32_l1
// Generated by build.sh

// Wrapper module
/home/xys/aps-mlir/circt/lib/Dialect/Cmt2/ModuleLibrary/firrtl/float_ip/FloatAdd.v

// HardFloat dependencies
/home/xys/aps-mlir/HardFloat/source/HardFloat_primitives.v
/home/xys/aps-mlir/HardFloat/source/HardFloat_rawFN.v
/home/xys/aps-mlir/HardFloat/source/isSigNaNRecFN.v
/home/xys/aps-mlir/HardFloat/source/fNToRecFN.v
/home/xys/aps-mlir/HardFloat/source/recFNToFN.v
/home/xys/aps-mlir/HardFloat/source/addRecFN.v
