#!/bin/bash
#===- build.sh - Build script for FIFO module ----------------------*- Bash -*-===#
#
# Generates FIRRTL extmodule declarations for parameterized FIFO
#
# Parameters:
#   width    - Data width (default: 8)
#   depth    - FIFO depth (default: 16)
#
# Outputs:
#   Fifo_w<width>_d<depth>.mlir  - FIRRTL extmodule with BlackBoxPathAnno
#   Fifo_w<width>_d<depth>.f     - Filelist for synthesis tools
#
#===------------------------------------------------------------------------===#

set -e

# Default parameters
WIDTH=8
DEPTH=16

# Parse named parameters
for arg in "$@"; do
  case $arg in
    width=*)
      WIDTH="${arg#*=}"
      ;;
    depth=*)
      DEPTH="${arg#*=}"
      ;;
    *)
      echo "Unknown parameter: $arg" >&2
      ;;
  esac
done

# Get script directory for Verilog file paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

MODULE_NAME="Fifo_w${WIDTH}_d${DEPTH}"
MLIR_FILE="${SCRIPT_DIR}/${MODULE_NAME}.mlir"
FILELIST="${SCRIPT_DIR}/${MODULE_NAME}.f"
SV_FILE="${SCRIPT_DIR}/fifo.sv"

# Generate annotations
ANNOTATIONS="[{class = \"firrtl.transforms.BlackBoxPathAnno\", path = \"${SV_FILE}\"}]"

# Generate MLIR file
cat > "${MLIR_FILE}" << EOF
module {
  firrtl.circuit "${MODULE_NAME}" {
    firrtl.extmodule @${MODULE_NAME}<WIDTH: i64 = ${WIDTH}, DEPTH: i64 = ${DEPTH}>(
      in clk: !firrtl.clock,
      in reset: !firrtl.uint<1>,
      in wr_en: !firrtl.uint<1>,
      in wr_data: !firrtl.uint<${WIDTH}>,
      out wr_ready: !firrtl.uint<1>,
      in rd_en: !firrtl.uint<1>,
      out rd_data: !firrtl.uint<${WIDTH}>,
      out rd_ready: !firrtl.uint<1>
    ) attributes {defname = "fifo", annotations = ${ANNOTATIONS}}
  }
}
EOF

# Generate filelist
cat > "${FILELIST}" << EOF
// Filelist for ${MODULE_NAME}
// Generated by build.sh (FIFO)

${SV_FILE}
EOF

echo "Generated: ${MLIR_FILE}"
echo "Generated: ${FILELIST}"
