// FIRRTLReg_1: Register with read/write interface
// Generated by pycmt2.stl
//
// This register updates unconditionally each cycle.
// Enable logic is handled externally by the CMT2->FIRRTL lowering.

module FIRRTLReg_1 (
    input  logic               clk,
    input  logic               rst,
    output logic [0:0] res0,
    input  logic [0:0] data
);
    logic [0:0] value;

    // Read output
    assign res0 = value;

    // Register update
    always_ff @(posedge clk) begin
        if (rst) begin
            value <= 1'h0;
        end else begin
            value <= data;
        end
    end

endmodule
