// Generated by CIRCT e9b3f1e70
module MultiCycleALU(
  input         clk,
                rst,
                start_enable,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:47
  output        start_ready,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:47
  input  [31:0] start_a,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:47
                start_b,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:47
  output        get_result_ready,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:74
  output [31:0] get_result_res0,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:74
  output        is_ready_ready,	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:84
                is_ready_res0	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:84
);

  wire        _GEN;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:47, :61
  wire [31:0] _GEN_0;
  wire [31:0] get_result_res0_0;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:74
  wire        _busy_res0;
  wire [31:0] _reg_b_res0;
  wire [31:0] _reg_a_res0;
  FIRRTLReg_32 reg_a (
    .clk  (clk),
    .rst  (rst),
    .res0 (_reg_a_res0),
    .data (start_a)
  );
  FIRRTLReg_32 reg_b (
    .clk  (clk),
    .rst  (rst),
    .res0 (_reg_b_res0),
    .data (start_b)
  );
  FIRRTLReg_32 reg_result (
    .clk  (clk),
    .rst  (rst),
    .res0 (get_result_res0_0),
    .data (_GEN_0)
  );
  FIRRTLReg_1 busy (
    .clk  (clk),
    .rst  (rst),
    .res0 (_busy_res0),
    .data (_GEN)	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:47, :61
  );
  wire        _GEN_1 = ~_busy_res0;
  wire        _GEN_2 = _GEN_1 & start_enable;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:47
  wire [32:0] _GEN_3 = {1'h0, _reg_a_res0} + {1'h0, _reg_b_res0};
  assign _GEN_0 = _GEN_3[31:0];
  assign _GEN = _busy_res0 & ~_GEN_2 ? 1'h0 : _GEN_2;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:47, :61
  wire        is_ready_res0_0 = ~_busy_res0;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:84
  assign start_ready = _GEN_1;
  assign get_result_ready = ~_busy_res0;
  assign get_result_res0 = get_result_res0_0;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:74
  assign is_ready_ready = 1'h1;
  assign is_ready_res0 = is_ready_res0_0;	// /home/uvxiao/circt-cmt2/build/../examples/PyCMT2/test_proc_simulation.py:84
endmodule

