#!/bin/bash
# Create a complete simulation workspace for CMT2 designs
# Supports both MLIR (.mlir) and PyCMT2 (.py) inputs

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"

usage() {
    echo "Usage: $0 <input-file> <workspace-dir> [--tb <testbench.sv>]"
    echo ""
    echo "Creates a complete simulation workspace with:"
    echo "  - Compiled RTL (SystemVerilog)"
    echo "  - Testbench (auto-generated or user-provided)"
    echo "  - Makefile for simulation"
    echo ""
    echo "Input can be:"
    echo "  - .mlir file: CMT2 MLIR directly"
    echo "  - .py file:   PyCMT2 Python script"
    echo ""
    echo "Options:"
    echo "  --tb <file>   Use custom testbench instead of auto-generated"
    echo ""
    echo "Examples:"
    echo "  $0 test.mlir my_sim/"
    echo "  $0 gcd.py gcd_sim/ --tb my_tb.sv"
    exit 1
}

if [[ $# -lt 2 ]]; then
    usage
fi

INPUT_FILE="$1"
WORKSPACE="$2"
CUSTOM_TB=""

# Parse additional arguments
shift 2
while [[ $# -gt 0 ]]; do
    case "$1" in
        --tb)
            CUSTOM_TB="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            usage
            ;;
    esac
done

if [[ ! -f "$INPUT_FILE" ]]; then
    echo "Error: Input file not found: $INPUT_FILE"
    exit 1
fi

# Get basename
EXT="${INPUT_FILE##*.}"
BASENAME="$(basename "$INPUT_FILE" ".$EXT")"

echo "=== Creating Simulation Workspace ==="
echo "Input:     $INPUT_FILE"
echo "Workspace: $WORKSPACE/"

# Create directory structure
mkdir -p "$WORKSPACE/rtl"
mkdir -p "$WORKSPACE/tb"
mkdir -p "$WORKSPACE/sim"
mkdir -p "$WORKSPACE/logs"

# Step 1: Compile to SystemVerilog
echo ""
echo "Step 1: Compiling design..."
"$SCRIPT_DIR/cmt2-to-sv.sh" "$INPUT_FILE" "$WORKSPACE/rtl"

# Move files to proper locations
if [[ -f "$WORKSPACE/rtl/$BASENAME.sv" ]]; then
    echo "  RTL generated: $WORKSPACE/rtl/$BASENAME.sv"
fi

# Step 2: Create or copy testbench
echo ""
echo "Step 2: Setting up testbench..."
if [[ -n "$CUSTOM_TB" && -f "$CUSTOM_TB" ]]; then
    cp "$CUSTOM_TB" "$WORKSPACE/tb/testbench.sv"
    echo "  Using custom testbench: $CUSTOM_TB"
else
    # Auto-generate a basic testbench
    cat > "$WORKSPACE/tb/testbench.sv" << 'EOF'
`timescale 1ns/1ps

// Auto-generated testbench
// Modify as needed for your design

module testbench;
  // Clock and reset
  logic clk;
  logic reset;

  // Clock generation: 100MHz (10ns period)
  initial clk = 0;
  always #5 clk = ~clk;

  // TODO: Instantiate your DUT here
  // Example:
  // MyModule dut (
  //   .clock(clk),
  //   .reset(reset)
  // );

  // Test sequence
  initial begin
    $display("=== Simulation Started ===");

    // Reset sequence
    reset = 1;
    repeat(10) @(posedge clk);
    reset = 0;
    $display("Reset released at time %0t", $time);

    // Run for some cycles
    repeat(100) @(posedge clk);

    $display("=== Simulation Complete ===");
    $finish;
  end

  // Timeout watchdog
  initial begin
    #100000;
    $display("ERROR: Simulation timeout!");
    $finish;
  end

  // VCD dump for waveform viewing
  initial begin
    $dumpfile("sim.vcd");
    $dumpvars(0, testbench);
  end
endmodule
EOF
    echo "  Generated basic testbench: $WORKSPACE/tb/testbench.sv"
    echo "  NOTE: Edit testbench.sv to instantiate your DUT"
fi

# Step 3: Create Makefile
echo ""
echo "Step 3: Creating Makefile..."
cat > "$WORKSPACE/sim/Makefile" << EOF
# Simulation Makefile
# Generated by create-sim-workspace.sh

DESIGN = $BASENAME
RTL_DIR = ../rtl
TB_DIR = ../tb
LOG_DIR = ../logs

# Simulator selection (iverilog by default)
SIM = iverilog
VVP = vvp

# Source files
RTL_SRC = \$(wildcard \$(RTL_DIR)/*.sv) \$(wildcard \$(RTL_DIR)/*.v)
TB_SRC = \$(wildcard \$(TB_DIR)/*.sv)

# Output
SIM_OUT = sim.out
VCD_OUT = sim.vcd

.PHONY: all compile run clean wave

all: run

compile: \$(SIM_OUT)

\$(SIM_OUT): \$(RTL_SRC) \$(TB_SRC)
	@echo "Compiling with iverilog..."
	\$(SIM) -g2012 -Wall -o \$@ \$(RTL_SRC) \$(TB_SRC) 2>&1 | tee \$(LOG_DIR)/compile.log
	@echo "Compilation complete"

run: \$(SIM_OUT)
	@echo "Running simulation..."
	cd .. && \$(VVP) sim/\$(SIM_OUT) 2>&1 | tee logs/sim.log
	@echo "Simulation complete. Log: \$(LOG_DIR)/sim.log"

wave: run
	@echo "Opening waveform viewer..."
	gtkwave \$(VCD_OUT) &

clean:
	rm -f \$(SIM_OUT) \$(VCD_OUT)
	rm -f \$(LOG_DIR)/*.log

# Verilator alternative
verilate:
	verilator --cc --exe --build -Wall \$(RTL_SRC) \$(TB_SRC)
EOF
echo "  Created: $WORKSPACE/sim/Makefile"

# Step 4: Create helper script
cat > "$WORKSPACE/run.sh" << 'EOF'
#!/bin/bash
# Quick run script
cd "$(dirname "$0")/sim"
make run
EOF
chmod +x "$WORKSPACE/run.sh"
echo "  Created: $WORKSPACE/run.sh"

# Summary
echo ""
echo "=== Workspace Created Successfully ==="
echo ""
echo "Directory structure:"
echo "  $WORKSPACE/"
echo "  ├── rtl/              # Generated SystemVerilog"
echo "  │   └── $BASENAME.sv"
echo "  ├── tb/               # Testbench"
echo "  │   └── testbench.sv"
echo "  ├── sim/              # Simulation files"
echo "  │   └── Makefile"
echo "  ├── logs/             # Log files"
echo "  └── run.sh            # Quick run script"
echo ""
echo "Next steps:"
echo "  1. Edit $WORKSPACE/tb/testbench.sv to instantiate your DUT"
echo "  2. Run: cd $WORKSPACE/sim && make run"
echo "  3. View waveforms: cd $WORKSPACE/sim && make wave"
